[package]
name = "hello_web"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
axum-sessions = "0.7"
tokio = { version = "1", features = ["full"] }
askama = "0.12"
serde = { version = "1.0", features = ["derive"] }
